import { HttpException, HttpStatus, Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { timingSafeEqual } from 'node:crypto';
import { MotcSmsDbService } from '@core/database/motc-sms-db.service';
import { MssqlQueryError } from '@core/database/mssql.error';
import { MotcSmsConfig, OtpConfig, SmsConfig } from '@core/config/configuration';
import {
  OtpPort,
  SendOtpCommand,
  SendOtpResult,
  VerifyOtpCommand,
} from '../../domain/ports/otp.port';
import { generateOtp, otpCharClass } from './otp-generator.util';

/** Latest OTP push row for a user+device (or by MessageID). */
interface PushRow {
  MessageID: number;
  DiffInSeconds: number;
  MessageBody: string;
}

/** SQL Server duplicate-key errors (PK violation / unique index). */
const DUPLICATE_KEY_ERRORS = new Set([2601, 2627]);
const INSERT_RETRIES = 5;

/**
 * OTP store + delivery + validation backed by the MOTC SMS gateway database
 * (client request 2026-08-25): the OTP we generate is INSERTed into
 * `MOTC_SMS_PushTable` following the client's documented INSERT — the row IS
 * the SMS delivery (the gateway pushes pending rows) — and OTP validation
 * reads the same table back, so no separate SMS call or OTP table is involved.
 *
 * - `MessageID` is generated by us (MAX+1, retried on a duplicate-key race)
 *   and doubles as the mobile `requestid`.
 * - `BusinessParam1/2` carry username + device IMEI by default, which is what
 *   lets validation target "the latest OTP issued to THIS user+device". Ops
 *   can pin them to static values (MOTC_SMS_BUSINESS_PARAM1/2), degrading
 *   verification to a MessageID-only lookup.
 * - The OTP travels inside `MessageBody` (SMS_MESSAGE_TEMPLATE with `{otp}`);
 *   verification extracts it with a template-derived pattern. The body and
 *   phone number are never logged (MotcSmsDbService redacts both params).
 * - Policy comes from OtpConfig: TTL, resend window, and max verify attempts
 *   (attempts + single-use are tracked in-memory per MessageID — the push
 *   table has no columns for them, same trade-off as the legacy adapter).
 */
@Injectable()
export class MotcSmsOtpRepository implements OtpPort {
  private readonly logger = new Logger(MotcSmsOtpRepository.name);
  private readonly cfg: OtpConfig;
  private readonly motc: MotcSmsConfig;
  private readonly messageTemplate: string;
  /** Pattern extracting the OTP back out of a stored MessageBody. */
  private readonly otpPattern: RegExp;
  /** Failed verify attempts per MessageID (no attempts column in the table). */
  private readonly attempts = new Map<string, number>();
  /** MessageIDs already verified successfully — single-use within the TTL. */
  private readonly consumed = new Set<string>();

  constructor(
    private readonly db: MotcSmsDbService,
    config: ConfigService,
  ) {
    this.cfg = config.getOrThrow<OtpConfig>('otp');
    this.motc = config.getOrThrow<MotcSmsConfig>('motcSms');
    this.messageTemplate = config.getOrThrow<SmsConfig>('sms').messageTemplate;
    // The table name is config-controlled (never user input) but interpolated
    // into SQL as an identifier, so keep it to identifier characters.
    if (!/^[A-Za-z0-9_.[\]]+$/.test(this.motc.table)) {
      throw new Error(`Invalid MOTC_SMS_TABLE "${this.motc.table}" — not a SQL identifier.`);
    }
    this.otpPattern = this.buildOtpPattern();
  }

  /** BusinessParam1/2 free for username+IMEI correlation (the default). */
  private get correlates(): boolean {
    return !this.motc.businessParam1 && !this.motc.businessParam2;
  }

  async send(cmd: SendOtpCommand): Promise<SendOtpResult> {
    const latest = await this.latestRowForSend(cmd);
    if (latest && latest.DiffInSeconds < this.cfg.resendWindowSeconds) {
      throw new HttpException(
        'An OTP was sent recently. Please wait before requesting another.',
        HttpStatus.TOO_MANY_REQUESTS,
      );
    }
    if (!cmd.phoneNumber) {
      throw new HttpException(
        'No registered phone number found for this user.',
        HttpStatus.CONFLICT,
      );
    }

    const otp = generateOtp(this.cfg);
    // Raw OTP goes only into MessageBody — never logged, never returned.
    const messageBody = this.messageTemplate.replace('{otp}', otp);
    const messageId = await this.insertMessage(cmd, messageBody);
    this.logger.log(`OTP push row queued (${cmd.purpose}) as MessageID=${messageId}.`);
    return { requestId: String(messageId) };
  }

  async verify(cmd: VerifyOtpCommand): Promise<boolean> {
    const row = this.correlates
      ? await this.latestRowFor(cmd.username, cmd.imei)
      : await this.rowByMessageId(cmd.requestId);
    if (!row) return false;
    const requestId = String(row.MessageID);
    // The verification must target the OTP the client was actually issued.
    if (cmd.requestId !== requestId) return false;
    if (this.consumed.has(requestId)) return false;
    if (row.DiffInSeconds > this.cfg.ttlSeconds) return false;

    const failed = this.attempts.get(requestId) ?? 0;
    if (failed >= this.cfg.maxAttempts) {
      this.logger.warn(`OTP request ${requestId} locked after ${failed} failed attempts.`);
      return false;
    }

    const expected = this.extractOtp(String(row.MessageBody ?? ''));
    if (!expected || !MotcSmsOtpRepository.safeEquals(expected, cmd.otp.trim())) {
      this.attempts.set(requestId, failed + 1);
      return false;
    }

    this.attempts.delete(requestId);
    this.consumed.add(requestId);
    return true;
  }

  /**
   * INSERT following the client's documented column list. MessageID is MAX+1;
   * a duplicate-key race with a concurrent insert is retried with a fresh id.
   */
  private async insertMessage(cmd: SendOtpCommand, messageBody: string): Promise<number> {
    const appId = this.motc.appId || null;
    for (let attempt = 1; attempt <= INSERT_RETRIES; attempt++) {
      const next = await this.db.query<{ NextId: number }>(
        `SELECT ISNULL(MAX(MessageID), 0) + 1 AS NextId FROM ${this.motc.table} WITH (NOLOCK)`,
      );
      const messageId = next[0]?.NextId ?? 1;
      try {
        await this.db.execute(
          `INSERT INTO ${this.motc.table}
             (MessageID, ToAddress, MessageBody, AddedTimeStamp, ProcessedState,
              ProcessedTimeStamp, Priority, ServiceID, SubjectID, LANGUAGE_ID,
              RecipientAddressType, MessageSendScheduleDateTime, MessageExpireMinutes,
              CustomerID, FromAddress, MaskMessageLog, ApplicationID,
              BusinessParam1, BusinessParam2)
           VALUES
             (@messageId, @toAddress, @messageBody, GETDATE(), @processedState,
              NULL, @priority, @serviceId, @subjectId, @languageId,
              @recipientAddressType, GETDATE(), @messageExpireMinutes,
              @customerId, @fromAddress, @maskMessageLog, @applicationId,
              @businessParam1, @businessParam2)`,
          {
            messageId,
            toAddress: cmd.phoneNumber,
            messageBody,
            processedState: this.motc.processedState,
            priority: this.motc.priority,
            serviceId: appId,
            subjectId: this.motc.subjectId || null,
            languageId: this.motc.languageId,
            recipientAddressType: this.motc.recipientAddressType,
            messageExpireMinutes: this.motc.messageExpireMinutes,
            customerId: this.motc.customerId || null,
            fromAddress: this.motc.fromAddress || appId,
            maskMessageLog: this.motc.maskMessageLog,
            applicationId: appId,
            businessParam1: this.motc.businessParam1 || cmd.username,
            businessParam2: this.motc.businessParam2 || cmd.imei,
          },
        );
        return messageId;
      } catch (err) {
        const sqlError = (err as MssqlQueryError).sqlErrorNumber;
        if (sqlError !== undefined && DUPLICATE_KEY_ERRORS.has(sqlError) && attempt < INSERT_RETRIES) {
          this.logger.warn(
            `MessageID ${messageId} raced a concurrent insert — retrying (${attempt}/${INSERT_RETRIES}).`,
          );
          continue;
        }
        throw err;
      }
    }
    throw new HttpException('Could not create the OTP request.', HttpStatus.INTERNAL_SERVER_ERROR);
  }

  /** Resend-window lookup: by user+device when correlating, else by phone. */
  private async latestRowForSend(cmd: SendOtpCommand): Promise<PushRow | undefined> {
    if (this.correlates) return this.latestRowFor(cmd.username, cmd.imei);
    if (!cmd.phoneNumber) return undefined;
    const rows = await this.db.query<PushRow>(
      `SELECT TOP 1 MessageID,
              DATEDIFF(SECOND, AddedTimeStamp, GETDATE()) AS DiffInSeconds,
              MessageBody
         FROM ${this.motc.table} WITH (NOLOCK)
        WHERE ToAddress = @toAddress
        ORDER BY MessageID DESC`,
      { toAddress: cmd.phoneNumber },
    );
    return rows[0];
  }

  /** Newest push row for this user+device (BusinessParam1/2 correlation). */
  private async latestRowFor(username: string, imei: string): Promise<PushRow | undefined> {
    const rows = await this.db.query<PushRow>(
      `SELECT TOP 1 MessageID,
              DATEDIFF(SECOND, AddedTimeStamp, GETDATE()) AS DiffInSeconds,
              MessageBody
         FROM ${this.motc.table} WITH (NOLOCK)
        WHERE BusinessParam1 = @username AND BusinessParam2 = @imei
        ORDER BY MessageID DESC`,
      { username, imei },
    );
    return rows[0];
  }

  /** Fallback when BusinessParams are pinned: fetch the issued row directly. */
  private async rowByMessageId(requestId: string): Promise<PushRow | undefined> {
    const messageId = Number(requestId);
    if (!Number.isInteger(messageId)) return undefined;
    const rows = await this.db.query<PushRow>(
      `SELECT MessageID,
              DATEDIFF(SECOND, AddedTimeStamp, GETDATE()) AS DiffInSeconds,
              MessageBody
         FROM ${this.motc.table} WITH (NOLOCK)
        WHERE MessageID = @messageId`,
      { messageId },
    );
    return rows[0];
  }

  /**
   * Derive the extraction pattern from the message template: everything is
   * matched literally except `{otp}`, which becomes a capture group of the
   * configured OTP charset. A template without `{otp}` degrades to "the
   * first OTP_LENGTH-character run of that charset".
   */
  private buildOtpPattern(): RegExp {
    const cls = otpCharClass(this.cfg);
    const escaped = this.messageTemplate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    if (escaped.includes('\\{otp\\}')) {
      return new RegExp(escaped.replace('\\{otp\\}', `(${cls}+)`));
    }
    this.logger.warn(
      'SMS_MESSAGE_TEMPLATE has no {otp} placeholder — OTP extraction falls back to the first charset run.',
    );
    return new RegExp(`(${cls}{${this.cfg.length}})`);
  }

  private extractOtp(messageBody: string): string | undefined {
    const match = this.otpPattern.exec(messageBody);
    if (!match) {
      this.logger.warn('Stored MessageBody did not match the OTP message template.');
      return undefined;
    }
    return match[1];
  }

  private static safeEquals(a: string, b: string): boolean {
    const bufA = Buffer.from(a);
    const bufB = Buffer.from(b);
    return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
  }
}
